# Generated by Django 3.0.8 on 2020-08-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileBooks',
            new_name='ProfileBook',
        ),
    ]
