# Generated by Django 3.0.8 on 2020-08-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200804_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileBook',
        ),
    ]
