# Generated by Django 3.0.8 on 2020-08-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200804_1702'),
        ('profiles', '0006_delete_profilebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='asked_books',
            field=models.ManyToManyField(through='profiles.AskBook', to='books.Book'),
        ),
    ]
