# Generated by Django 3.0.8 on 2020-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200810_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pic_url',
            field=models.CharField(default='missingbook.png', max_length=54),
        ),
    ]
