# Generated by Django 3.0.8 on 2020-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200810_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
