# Generated by Django 3.0.8 on 2020-08-02 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('books_count', models.IntegerField(default=1)),
                ('authors', models.CharField(max_length=254)),
                ('publication_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(999)])),
                ('title', models.CharField(max_length=254)),
                ('language_code', models.CharField(default='eng', max_length=3)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('ratings_1', models.IntegerField(blank=True, null=True)),
                ('ratings_2', models.IntegerField(blank=True, null=True)),
                ('ratings_3', models.IntegerField(blank=True, null=True)),
                ('ratings_4', models.IntegerField(blank=True, null=True)),
                ('ratings_5', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
