# Generated by Django 3.0.8 on 2020-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200802_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='v_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
