# Generated by Django 3.0.8 on 2020-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200804_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
